const  infoDataList = [
    {Num: 1,Title: "Title",Date: "Date"},
    {Num: 2,Title: "Title",Date: "Date"},
    {Num: 3,Title: "Title",Date: "Date"},
    {Num: 4,Title: "Title",Date: "Date"},
    {Num: 5,Title: "Title",Date: "Date"},
    {Num: 6,Title: "Title",Date: "Date"},
    {Num: 7,Title: "Title",Date: "Date"},
    {Num: 8,Title: "Title",Date: "Date"},
    {Num: 9,Title: "Title",Date: "Date"},
    {Num: 10,Title: "Title",Date: "Date"},
    {Num: 11,Title: "Title",Date: "Date"},
    {Num: 12,Title: "Title",Date: "Date"},
    {Num: 13,Title: "Title",Date: "Date"},
    {Num: 14,Title: "Title",Date: "Date"},
    {Num: 15,Title: "Title",Date: "Date"},
    {Num: 16,Title: "Title",Date: "Date"},
    {Num: 17,Title: "Title",Date: "Date"},
    {Num: 18,Title: "Title",Date: "Date"},
    {Num: 19,Title: "Title",Date: "Date"},
    {Num: 20,Title: "Title",Date: "Date"},
];
export default infoDataList;